# Generated by Django 4.0.6 on 2022-08-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_title_post_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='contenido',
        ),
    ]
