# Generated by Django 4.0.6 on 2022-08-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_body_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Publicaciones', max_length=255),
        ),
    ]
